import request from './request';
export const getWarehouseList = (params) => request({ url: '/warehouse/list', method: 'get', params });
export const getWarehouseById = (id) => request({ url: `/warehouse/${id}`, method: 'get' });
export const createWarehouse = (data) => request({ url: '/warehouse', method: 'post', data });
export const updateWarehouse = (data) => request({ url: '/warehouse', method: 'put', data });
export const deleteWarehouse = (id) => request({ url: `/warehouse/${id}`, method: 'delete' });
export const getZoneList = (params) => request({ url: '/warehouse/zone/list', method: 'get', params });
export const getZoneById = (id) => request({ url: `/warehouse/zone/${id}`, method: 'get' });
export const createZone = (data) => request({ url: '/warehouse/zone', method: 'post', data });
export const updateZone = (data) => request({ url: '/warehouse/zone', method: 'put', data });
export const deleteZone = (id) => request({ url: `/warehouse/zone/${id}`, method: 'delete' });
export const getRackList = (params) => request({ url: '/warehouse/rack/list', method: 'get', params });
export const getRackById = (id) => request({ url: `/warehouse/rack/${id}`, method: 'get' });
export const createRack = (data) => request({ url: '/warehouse/rack', method: 'post', data });
export const updateRack = (data) => request({ url: '/warehouse/rack', method: 'put', data });
export const deleteRack = (id) => request({ url: `/warehouse/rack/${id}`, method: 'delete' });
export const getBinList = (params) => request({ url: '/warehouse/bin/list', method: 'get', params });
export const getBinById = (id) => request({ url: `/warehouse/bin/${id}`, method: 'get' });
export const createBin = (data) => request({ url: '/warehouse/bin', method: 'post', data });
export const updateBin = (data) => request({ url: '/warehouse/bin', method: 'put', data });
export const deleteBin = (id) => request({ url: `/warehouse/bin/${id}`, method: 'delete' });
